server:
  port: 8081

spring:
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        type: sync

logging:
  level:
    root: info
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: info